### ISSUE TITLE
openvtx.org -failing to flash new firmware

### ISSUE THREAD

**Issue by pitts-mo** [OpenVTx/Openvtx-configurator#2]
Sorry, this is a bit generic. However, discord suggests others may be hitting similar issue attempting to update flash using openvtx.org.

log of issue i see:
[info][flash] attempting msp passthrough                                                                                                              
[warning][flash] passthrough failed                                                                                                                   
[debug][flash] Error: unsupported msp version                                                                                                         
[info][flash] attempting to reboot into bootloader
[info][openvtx] trying vtxType SA
[warning][serial] Error: The device has been lost.
[error][serial] Error: The device has been lost.
[warning][serial] Error: The device has been lost.

My usage details:
EWRF E7082VM
matek f722mini se w/inav 5.1.0 
lubuntu 22.04
chrome (current)

My workaround attempts:
use platformio to re-flash bootloader 0.1.0 from source -still can not flash openvtx 0.2.0 from opentx.org
use platformio to re-flash firmware 0.2.0 from source -openvtx firmware appears to work fine but I still can not re-flash openvtx 0.2.0 from opentx.org

**Comment by bkleiner** [comment]
```
[debug][flash] Error: unsupported msp version
```
this is likely your issue, seems inav does not meet the msp requirement. i will do some digging on that.
in the meantime, can you try flashing your FC to betaflight and see if the flash succeeds there? just so we know everything else is in working order.

**Comment by pitts-mo** [comment]
Ok. I should be able to test this within the next few days. Thanks. -p

**Comment by pitts-mo** [comment]
ok, 
All test flash attempts from OpenVTX.org while betaflight was loaded on my Matek F722mini se were successful.
(EWRF_E7082VM: -> 0.2.0 -> 0.1.0 -> 0.2.0)

After putting inav 5.1.0 back on my MatekF722mini se OpenVTX.org fails to flash. However, this time I have noticed OpenVTX.org is leaving the inav FC in DFU mode...

Maybe add a detection system that gracefully selects appropriate flash method Or just a user option to fall back to SA flash mode?

-p

**Comment by JyeSmith** [comment]
Looks like the logic here is a little wrong.  The major version is fine but it fails the minor version check.  The if statement just needs a little rejig.

`if (version.payload[1] < 1 || version.payload[2] < 42) {`

https://github.com/OpenVTx/Openvtx-configurator/blob/master/src/serial/msp.ts#L213

Inav is on 2.4

```
#define API_VERSION_MAJOR                   2
#define API_VERSION_MINOR                   4
```

https://github.com/iNavFlight/inav/blob/master/src/main/msp/msp_protocol.h#L61

**Comment by JyeSmith** [comment]
We can also print the version in the error for future users.

**Comment by bkleiner** [comment]
right, good call, probably just treat it as the pseudo semver it is see #3

**Comment by bkleiner** [comment]
@pitts-mo changes from #3 are online, please give it another try. 
flash succeeds now on my test setup with inav 5.1.0

**Comment by pitts-mo** [comment]
Like a dream :-) thank you.
-p

[info][flash] attempting msp passthrough
[debug][msp] api version 0.2.4
[debug][msp] fc variant INAV
[debug][msp] fc version 5.1.0
[debug][msp] found SA on port 3
[info][flash] detected vtx type SA
[info][flash] attempting to reboot into bootloader
[info][flash] detected bootloader
[info][flash] flashing 19880 bytes
[debug][xmodem] sending block 1/156 try 0
...
[debug][xmodem] sending block 156/156 try 0
[info][flash] success
